export interface AdmissionCase {
  admissionYear: number;
  graduateUniversity: string;
  graduateMajor: string;
  undergraduateUniversity: string;
  undergraduateMajor: string;
  gpa: number;
  toefl: number;
  gre: number;
  internshipExperience: string;
  researchExperience: string;
  share: string;
}

export const admissionCaseData: AdmissionCase[] = [
  {
    admissionYear: 2020 + Math.floor(Math.random() * 4),
    graduateUniversity: "普林斯顿大学",
    graduateMajor: "计算机科学",
    undergraduateUniversity: "上海交通大学",
    undergraduateMajor: "计算机科学与技术",
    gpa: (30 + Math.floor(Math.random() * 10)) / 10.0,
    toefl: 100 + Math.floor(Math.random() * 20),
    gre: 310 + Math.floor(Math.random() * 20),
    internshipExperience: "京东算法岗实习、美团算法岗实习",
    researchExperience: "论文 1 篇",
    share: "首先要明确的是，你究竟想学什么专业？我见过不少同学，快到申请的时候了，还想不清楚自己研究生想读的专业和方向。我觉得研究生申请不同于本科，本科申请一般是先想好学校再想专业。但研究生相反，而且地理位置因素也是必须要纳入考量的，因为研究生读完之后面临的问题就是找工了。\n\n其次就是选校。排名和地理位置要放在一起综合考虑。可以拿出了两个榜单，一个是美国大学排名，一个是美国大学cs排名。对比一下，除去我所力不能及的学校（Stanford之类的），就得出了我申请的十所学校。"
  },
  {
    admissionYear: 2020 + Math.floor(Math.random() * 4),
    graduateUniversity: "普林斯顿大学",
    graduateMajor: "计算机科学",
    undergraduateUniversity: "上海交通大学",
    undergraduateMajor: "计算机科学与技术",
    gpa: (30 + Math.floor(Math.random() * 10)) / 10.0,
    toefl: 100 + Math.floor(Math.random() * 20),
    gre: 310 + Math.floor(Math.random() * 20),
    internshipExperience: "京东算法岗实习、美团算法岗实习",
    researchExperience: "论文 1 篇",
    share: "首先要明确的是，你究竟想学什么专业？我见过不少同学，快到申请的时候了，还想不清楚自己研究生想读的专业和方向。我觉得研究生申请不同于本科，本科申请一般是先想好学校再想专业。但研究生相反，而且地理位置因素也是必须要纳入考量的，因为研究生读完之后面临的问题就是找工了。\n\n其次就是选校。排名和地理位置要放在一起综合考虑。可以拿出了两个榜单，一个是美国大学排名，一个是美国大学cs排名。对比一下，除去我所力不能及的学校（Stanford之类的），就得出了我申请的十所学校。"
  },
  {
    admissionYear: 2020 + Math.floor(Math.random() * 4),
    graduateUniversity: "普林斯顿大学",
    graduateMajor: "计算机科学",
    undergraduateUniversity: "上海交通大学",
    undergraduateMajor: "计算机科学与技术",
    gpa: (30 + Math.floor(Math.random() * 10)) / 10.0,
    toefl: 100 + Math.floor(Math.random() * 20),
    gre: 310 + Math.floor(Math.random() * 20),
    internshipExperience: "京东算法岗实习、美团算法岗实习",
    researchExperience: "论文 1 篇",
    share: "首先要明确的是，你究竟想学什么专业？我见过不少同学，快到申请的时候了，还想不清楚自己研究生想读的专业和方向。我觉得研究生申请不同于本科，本科申请一般是先想好学校再想专业。但研究生相反，而且地理位置因素也是必须要纳入考量的，因为研究生读完之后面临的问题就是找工了。\n\n其次就是选校。排名和地理位置要放在一起综合考虑。可以拿出了两个榜单，一个是美国大学排名，一个是美国大学cs排名。对比一下，除去我所力不能及的学校（Stanford之类的），就得出了我申请的十所学校。"
  },
  {
    admissionYear: 2020 + Math.floor(Math.random() * 4),
    graduateUniversity: "普林斯顿大学",
    graduateMajor: "计算机科学",
    undergraduateUniversity: "上海交通大学",
    undergraduateMajor: "计算机科学与技术",
    gpa: (30 + Math.floor(Math.random() * 10)) / 10.0,
    toefl: 100 + Math.floor(Math.random() * 20),
    gre: 310 + Math.floor(Math.random() * 20),
    internshipExperience: "京东算法岗实习、美团算法岗实习",
    researchExperience: "论文 1 篇",
    share: "首先要明确的是，你究竟想学什么专业？我见过不少同学，快到申请的时候了，还想不清楚自己研究生想读的专业和方向。我觉得研究生申请不同于本科，本科申请一般是先想好学校再想专业。但研究生相反，而且地理位置因素也是必须要纳入考量的，因为研究生读完之后面临的问题就是找工了。\n\n其次就是选校。排名和地理位置要放在一起综合考虑。可以拿出了两个榜单，一个是美国大学排名，一个是美国大学cs排名。对比一下，除去我所力不能及的学校（Stanford之类的），就得出了我申请的十所学校。"
  },
  {
    admissionYear: 2020 + Math.floor(Math.random() * 4),
    graduateUniversity: "普林斯顿大学",
    graduateMajor: "金融",
    undergraduateUniversity: "上海交通大学",
    undergraduateMajor: "金融",
    gpa: (30 + Math.floor(Math.random() * 10)) / 10.0,
    toefl: 100 + Math.floor(Math.random() * 20),
    gre: 310 + Math.floor(Math.random() * 20),
    internshipExperience: "某某证券实习、某某银行实习",
    researchExperience: "商业战略分析研究",
    share: "美研金融专业涉及领域广泛，从投资银行到风险管理，从量化分析到资本市场，每个子领域都有其独特的职业路径和学术要求。申请者应首先明确自己的职业规划，是希望进入投资银行、基金公司还是监管机构？这将直接影响你的课程选择、实习经历和学术研究方向。"
  },
  {
    admissionYear: 2020 + Math.floor(Math.random() * 4),
    graduateUniversity: "普林斯顿大学",
    graduateMajor: "金融",
    undergraduateUniversity: "上海交通大学",
    undergraduateMajor: "金融",
    gpa: (30 + Math.floor(Math.random() * 10)) / 10.0,
    toefl: 100 + Math.floor(Math.random() * 20),
    gre: 310 + Math.floor(Math.random() * 20),
    internshipExperience: "某某证券实习、某某银行实习",
    researchExperience: "商业战略分析研究",
    share: "美研金融专业涉及领域广泛，从投资银行到风险管理，从量化分析到资本市场，每个子领域都有其独特的职业路径和学术要求。申请者应首先明确自己的职业规划，是希望进入投资银行、基金公司还是监管机构？这将直接影响你的课程选择、实习经历和学术研究方向。"
  },
  {
    admissionYear: 2020 + Math.floor(Math.random() * 4),
    graduateUniversity: "普林斯顿大学",
    graduateMajor: "金融",
    undergraduateUniversity: "上海交通大学",
    undergraduateMajor: "金融",
    gpa: (30 + Math.floor(Math.random() * 10)) / 10.0,
    toefl: 100 + Math.floor(Math.random() * 20),
    gre: 310 + Math.floor(Math.random() * 20),
    internshipExperience: "某某证券实习、某某银行实习",
    researchExperience: "商业战略分析研究",
    share: "美研金融专业涉及领域广泛，从投资银行到风险管理，从量化分析到资本市场，每个子领域都有其独特的职业路径和学术要求。申请者应首先明确自己的职业规划，是希望进入投资银行、基金公司还是监管机构？这将直接影响你的课程选择、实习经历和学术研究方向。"
  }
]

export function getAdmissionCasesByUniversity(graduateUniversity: string) {
  let indexes: number[] = [];
  for (let i = 0; i < admissionCaseData.length; i++) {
    if (admissionCaseData[i]["graduateUniversity"] === graduateUniversity) {
      indexes.push(i)
    }
  }
  return indexes.map(index => admissionCaseData[index])
}


